name: Release Workflow

on:
  push:
    branches: [main, beta]

jobs:
  unit_test:
    name: Unit Test
    uses: trivelaapp/go-kit/.github/workflows/unit_test.yaml@main
  versioning:
    name: Define next release version
    runs-on: ubuntu-20.04
    needs: unit_test
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: installs plugins
        run: |
          npm install -g lerna
          npm install -D semantic-release-monorepo @semantic-release/commit-analyzer @semantic-release/release-notes-generator @semantic-release/github
      - name: run lerna with semantic release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: lerna exec --concurrency 1 -- npx semantic-release --tag-format='${LERNA_PACKAGE_NAME}/v\${version}'
